/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_andevcon_app_Example */

#ifndef _Included_com_andevcon_app_Example
#define _Included_com_andevcon_app_Example
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_andevcon_app_Example
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_andevcon_app_Example_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
