/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_andevcon_app_CPlusPlusBridge */

#ifndef _Included_com_andevcon_app_CPlusPlusBridge
#define _Included_com_andevcon_app_CPlusPlusBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_andevcon_app_CPlusPlusBridge
 * Method:    getEncryptedID
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_andevcon_app_CPlusPlusBridge_getEncryptedID
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
